# Generated by Django 3.1.7 on 2021-03-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_equipamento',
            options={'ordering': ['descricao']},
        ),
    ]
