# Generated by Django 3.1.7 on 2021-03-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_auto_20210321_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='equipamentos.bairro'),
            preserve_default=False,
        ),
    ]
