# Generated by Django 6.0.3 on 2026-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20221018_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemasrelatados',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
