# Generated by Django 3.2.10 on 2022-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento_Atuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guias_Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cadastur', models.CharField(max_length=2, unique=True)),
                ('validade_cadastur', models.DateField(verbose_name='Validade Cadastur')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('instagram', models.CharField(max_length=60, unique=True)),
                ('facebook', models.CharField(max_length=60, unique=True)),
                ('site', models.CharField(max_length=60, unique=True)),
                ('categoria', models.ManyToManyField(to='guias.Categoria')),
                ('idiomas', models.ManyToManyField(to='guias.Idiomas')),
                ('segmento_de_atuacao', models.ManyToManyField(to='guias.Segmento_Atuacao')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
