# Generated by Django 3.2.10 on 2022-03-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guias_turismo',
            options={'ordering': ['nome'], 'verbose_name': 'Guia de Turismo Receptivo', 'verbose_name_plural': 'Guias de Turismo Receptivo'},
        ),
        migrations.AlterModelOptions(
            name='idiomas',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterModelOptions(
            name='segmento_atuacao',
            options={'verbose_name': 'Segmento de Atuação', 'verbose_name_plural': 'Segmentos de Atuação'},
        ),
        migrations.AlterField(
            model_name='guias_turismo',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guias_turismo',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guias_turismo',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guias_turismo',
            name='site',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='guias_turismo',
            name='telefone',
            field=models.CharField(default='22000000000', max_length=11),
        ),
    ]
