# Generated by Django 3.2.10 on 2022-03-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0003_alter_guias_turismo_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guias_turismo',
            name='cadastur',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
