# Generated by Django 3.2.9 on 2021-12-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cadastur',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
