# Generated by Django 3.2.9 on 2021-12-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_cidade_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('estado', 'nome')},
        ),
    ]
