# Generated by Django 3.2.13 on 2022-08-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20220310_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.cidade'),
        ),
    ]
