# Generated by Django 3.2.13 on 2022-08-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_usuario_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.cidade'),
        ),
    ]
