# Generated by Django 3.2.9 on 2021-12-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['user', 'dt_Chegada', 'dt_Saida'], 'verbose_name': 'Viagem', 'verbose_name_plural': 'Viagens'},
        ),
    ]
