# Generated by Django 3.2.10 on 2022-02-17 20:57

import contas.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0002_alter_viagem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='senha',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='cadastur_empresa_transporte',
            field=models.CharField(max_length=14, validators=[contas.functions.validate_CADASTUR]),
        ),
    ]
