# Generated by Django 3.2.10 on 2022-02-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0003_auto_20220217_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='cidade_origem',
            field=models.CharField(default='NH', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viagem',
            name='estado_origem',
            field=models.CharField(default='NH', max_length=120),
            preserve_default=False,
        ),
    ]
