# Generated by Django 3.2.10 on 2022-02-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0004_auto_20220219_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='restaurante_reservado',
            field=models.BooleanField(default=False, verbose_name='Restaurante reservado?'),
        ),
    ]
