# Generated by Django 3.2.10 on 2022-02-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_usuario_cadastur'),
        ('senhas', '0005_viagem_restaurante_reservado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cidade_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.cidade'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='estado_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas.estado'),
        ),
    ]
