# Generated by Django 3.2.10 on 2022-02-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0006_auto_20220222_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cnpj_empresa_transporte',
            field=models.CharField(max_length=14),
        ),
    ]
