# Generated by Django 3.2.10 on 2022-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0008_auto_20220222_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_turismo',
            name='outros',
            field=models.CharField(default='', max_length=60),
        ),
    ]
