# Generated by Django 3.2.10 on 2022-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0009_viagem_turismo_outros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cadastur_empresa_transporte',
            field=models.CharField(max_length=14),
        ),
    ]
