# Generated by Django 3.2.10 on 2022-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0011_alter_viagem_turismo_outros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cnpj_empresa_transporte',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='viagem_turismo',
            name='cadastur_guia',
            field=models.CharField(max_length=14),
        ),
    ]
