# Generated by Django 3.2.10 on 2022-03-09 18:17

import contas.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0012_auto_20220309_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='cnpj_empresa_transporte',
            field=models.CharField(max_length=14, validators=[contas.functions.validate_CNPJ]),
        ),
    ]
