# Generated by Django 3.2.10 on 2022-03-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0014_auto_20220309_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem_turismo',
            name='telefone',
        ),
        migrations.AddField(
            model_name='viagem',
            name='contato_responsavel',
            field=models.CharField(default=None, max_length=18),
        ),
        migrations.AddField(
            model_name='viagem',
            name='responsavel_viagem',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
