# Generated by Django 3.2.10 on 2022-03-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0016_alter_viagem_cadastur_empresa_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_turismo',
            name='telefone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
