# Generated by Django 3.2.10 on 2022-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0017_viagem_turismo_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem_turismo',
            name='outros',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
