# Generated by Django 3.1.4 on 2022-04-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0019_auto_20220413_1325'),
        ('senhas', '0019_auto_20220407_1936'),
    ]

    operations = [
    ]
