# Generated by Django 3.2.10 on 2022-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0019_auto_20220413_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_turismo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
