# Generated by Django 3.1.4 on 2022-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0020_viagem_turismo_ativo'),
        ('senhas', '0020_merge_20220413_1335'),
    ]

    operations = [
    ]
