# Generated by Django 4.0.6 on 2022-07-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('senhas', '0022_alter_viagem_estado_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
