# Generated by Django 3.1.4 on 2023-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0022_auto_20221018_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem_turismo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
