# Generated by Django 4.0.6 on 2022-07-26 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0023_alter_viagem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem_turismo',
            name='viagem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='senhas.viagem'),
        ),
    ]
