# Generated by Django 4.0.6 on 2022-07-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0024_alter_viagem_turismo_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem_turismo',
            name='viagem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senhas.viagem'),
        ),
    ]
