# Generated by Django 3.2.13 on 2022-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0025_alter_viagem_turismo_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='senha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
