# Generated by Django 3.2.13 on 2022-08-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0026_alter_viagem_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='dt_Saida',
            field=models.DateField(null=True, verbose_name='Data Saída'),
        ),
    ]
