# Generated by Django 3.2.13 on 2022-08-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0027_alter_viagem_dt_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='dt_Saida',
            field=models.DateField(blank=True, null=True, verbose_name='Data Saída'),
        ),
    ]
