# Generated by Django 3.2.13 on 2022-08-23 18:31

from django.db import migrations, models
import senhas.validations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0028_alter_viagem_dt_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='nome',
            field=models.CharField(max_length=60, unique=True, validators=[senhas.validations.validate_nome]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='cadastur_empresa_transporte',
            field=models.CharField(max_length=18, validators=[senhas.validations.validate_Cadastur]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='cnpj_empresa_transporte',
            field=models.CharField(max_length=18, validators=[senhas.validations.validate_CNPJ]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='quant_passageiros',
            field=models.PositiveSmallIntegerField(validators=[senhas.validations.validate_passageiros]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='responsavel_viagem',
            field=models.CharField(default=None, max_length=120, validators=[senhas.validations.validate_nome]),
        ),
        migrations.AlterField(
            model_name='viagem_turismo',
            name='cadastur_guia',
            field=models.CharField(max_length=18, validators=[senhas.validations.validate_Cadastur]),
        ),
        migrations.AlterField(
            model_name='viagem_turismo',
            name='celular',
            field=models.CharField(max_length=18, validators=[senhas.validations.validate_celular]),
        ),
        migrations.AlterField(
            model_name='viagem_turismo',
            name='nome_guia',
            field=models.CharField(max_length=60, validators=[senhas.validations.validate_nome]),
        ),
        migrations.AlterField(
            model_name='viagem_turismo',
            name='telefone',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[senhas.validations.validate_telefone]),
        ),
    ]
