# Generated by Django 3.2.10 on 2023-06-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0018_links_menu'),
        ('senhas', '0030_auto_20220914_1402'),
        ('senhas', '0030_auto_20230123_1156'),
    ]

    operations = [
    ]
