# Generated by Django 6.0.3 on 2026-03-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senhas', '0023_viagem_turismo_ativo'),
        ('senhas', '0031_merge_20230601_1702'),
    ]

    operations = [
    ]
